[package]
name = "larmorx-ants"
description = "ANTs tools ported to Rust for larmorx (antsApplyTransforms, ...)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
larmorx-core.workspace = true
larmorx-interp.workspace = true
larmorx-io.workspace = true
larmorx-transform.workspace = true
rayon.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
